sgx_status_t wc_test(sgx_enclave_id_t eid, int* retval, void* args);
sgx_status_t wc_benchmark_test(sgx_enclave_id_t eid, int* retval, void* args);
sgx_status_t enc_wolfSSL_Init(sgx_enclave_id_t eid, int* retval);
sgx_status_t enc_wolfSSL_Debugging_ON(sgx_enclave_id_t eid);
sgx_status_t enc_wolfSSL_Debugging_OFF(sgx_enclave_id_t eid);
sgx_status_t enc_wolfTLSv1_2_client_method(sgx_enclave_id_t eid, long int* retval);
sgx_status_t enc_wolfTLSv1_2_server_method(sgx_enclave_id_t eid, long int* retval);
sgx_status_t enc_wolfSSL_CTX_new(sgx_enclave_id_t eid, long int* retval, long int method);
sgx_status_t enc_wolfSSL_CTX_use_PrivateKey_buffer(sgx_enclave_id_t eid, int* retval, long int ctxId, const unsigned char* buf, long int sz, int type);
sgx_status_t enc_wolfSSL_CTX_load_verify_buffer(sgx_enclave_id_t eid, int* retval, long int ctxId, const unsigned char* buf, long int sz, int type);
sgx_status_t enc_wolfSSL_CTX_use_certificate_chain_buffer_format(sgx_enclave_id_t eid, int* retval, long int ctxId, const unsigned char* buf, long int sz, int type);
sgx_status_t enc_wolfSSL_CTX_use_certificate_buffer(sgx_enclave_id_t eid, int* retval, long int ctxId, const unsigned char* buf, long int sz, int type);
sgx_status_t enc_wolfSSL_CTX_set_cipher_list(sgx_enclave_id_t eid, int* retval, long int ctxId, const char* list);
sgx_status_t enc_wolfSSL_new(sgx_enclave_id_t eid, long int* retval, long int ctxId);
sgx_status_t enc_wolfSSL_set_fd(sgx_enclave_id_t eid, int* retval, long int sslId, int fd);
sgx_status_t enc_wolfSSL_connect(sgx_enclave_id_t eid, int* retval, long int sslId);
sgx_status_t enc_wolfSSL_write(sgx_enclave_id_t eid, int* retval, long int sslId, const void* in, int sz);
sgx_status_t enc_wolfSSL_get_error(sgx_enclave_id_t eid, int* retval, long int sslId, int ret);
sgx_status_t enc_wolfSSL_read(sgx_enclave_id_t eid, int* retval, long int sslId, void* out, int sz);
sgx_status_t enc_wolfSSL_free(sgx_enclave_id_t eid, long int sslId);
sgx_status_t enc_wolfSSL_CTX_free(sgx_enclave_id_t eid, long int ctxId);
sgx_status_t enc_wolfSSL_Cleanup(sgx_enclave_id_t eid, int* retval);
